name: telegram_stickers_import_example
description: Demonstrates how to use the telegram_stickers_import plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  telegram_stickers_import:
    path: ../
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/